/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "kmalloc.h"
#include "kmalloc_util.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_InitialHeap(void);
extern void test_SimpleMallocFree(void);
extern void test_MallocTooBig(void);
extern void test_MallocMaxSize(void);
extern void test_MultipleMalloc(void);
extern void test_MultipleFreeCoalesceTop(void);
extern void test_MultipleFreeCoalesceBottom(void);
extern void test_MultipleFreeCoalesceBoth(void);
extern void test_MallocSplit(void);
extern void test_MallocShouldNotSplitSmallChunk(void);
extern void test_MallocLastChunk(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("tests/TestMalloc.c");
  RUN_TEST(test_InitialHeap, 69);
  RUN_TEST(test_SimpleMallocFree, 95);
  RUN_TEST(test_MallocTooBig, 140);
  RUN_TEST(test_MallocMaxSize, 152);
  RUN_TEST(test_MultipleMalloc, 191);
  RUN_TEST(test_MultipleFreeCoalesceTop, 249);
  RUN_TEST(test_MultipleFreeCoalesceBottom, 297);
  RUN_TEST(test_MultipleFreeCoalesceBoth, 323);
  RUN_TEST(test_MallocSplit, 388);
  RUN_TEST(test_MallocShouldNotSplitSmallChunk, 392);
  RUN_TEST(test_MallocLastChunk, 396);

  return suite_teardown(UnityEnd());
}
