/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "kmalloc.h"
#include "kmalloc_util.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ListAddSingle(void);
extern void test_ListAddMultiple(void);
extern void test_ListRemoveSingle(void);
extern void test_ListRemoveEmpty(void);
extern void test_ListRemoveUntilEmpty(void);
extern void test_ListRemoveOneFromMultiple(void);
extern void test_ListRemoveInternalSingle(void);
extern void test_ListRemoveInternalMultipleNotHead(void);
extern void test_ListRemoveInternalMultipleHead(void);
extern void test_ListRemoveInternalUntilEmpty(void);
extern void test_ListMultipleAddRemove(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("tests/TestMallocUtil.c");
  RUN_TEST(test_ListAddSingle, 16);
  RUN_TEST(test_ListAddMultiple, 29);
  RUN_TEST(test_ListRemoveSingle, 50);
  RUN_TEST(test_ListRemoveEmpty, 66);
  RUN_TEST(test_ListRemoveUntilEmpty, 79);
  RUN_TEST(test_ListRemoveOneFromMultiple, 100);
  RUN_TEST(test_ListRemoveInternalSingle, 124);
  RUN_TEST(test_ListRemoveInternalMultipleNotHead, 139);
  RUN_TEST(test_ListRemoveInternalMultipleHead, 161);
  RUN_TEST(test_ListRemoveInternalUntilEmpty, 182);
  RUN_TEST(test_ListMultipleAddRemove, 202);

  return suite_teardown(UnityEnd());
}
